INSERT INTO vehicle.vehicles (
    source,
    brand,
    model,
    version,
    manufacture_year,
    license_plate,
    seats,
    transmission,
    fuel_type,
    status
) VALUES
    (
        'COMPANY_OWNED',
        'Toyota',
        'Camry',
        '2.5Q',
        2024,
        '51A-888.99',
        5,
        'AUTOMATIC',
        'GASOLINE',
        'ACTIVE'
    ),
    (
        'HOST_OWNED',
        'Honda',
        'CR-V',
        'L',
        2023,
        '59C-321.45',
        7,
        'AUTOMATIC',
        'GASOLINE',
        'ACTIVE'
    ),
    (
        'COMPANY_OWNED',
        'VinFast',
        'VF8',
        'Plus',
        2024,
        '51K-567.89',
        5,
        'AUTOMATIC',
        'ELECTRIC',
        'ACTIVE'
    )
ON CONFLICT (license_plate) DO NOTHING;
